### ISSUE TITLE
Setting the cookie domain and path

### ISSUE THREAD

**Issue by alexweissman** [gbirke/rememberme#13]
I'm using the example code to create the remember me cookie in my login route (`/public/account/login`):

```
// If the user wants to be remembered, create Rememberme cookie
if(!empty($data['rememberme'])) {
    $app->remember_me->createCookie($user->id);
} else {
    $app->remember_me->clearCookie();
}
```

However, the cookie is now limited in visibility to requests to `/public/account/login`.  How can I set the cookie path here via your API?

**Comment by gbirke** [comment]
Just put the following line before your code (or on the line after creating the RememberMe object):

```php
$app->remember_me->getCookie()->setPath("/");
```

Thanks for the question, I'll make it easier to set your own Cookie instance in version 2.

**Comment by alexweissman** [comment]
Yup, that's what I [ended up doing](https://github.com/alexweissman/UserFrosting/blob/dev/userfrosting/middleware/usersession/UserSession.php#L30).  It would also be good if we could set the cookie name and other parameters in the `createCookie` method as well.

**Comment by arvidastrom** [comment]
Also if you change the path and get "saved" by the cookie it will discard previously defined paths. Or as far as I can understand. 

What I've done is prior to checking the cookie with (in this example) 
`$app->remember_me->login()`

I do this to ensure that the path is still '/' after cookie is renewed.

`
$cookie = $app->remember_me->getCookie();
$cookie->setPath('/');
$app->remember_me->login()
`

**Comment by gbirke** [comment]
In Version 2.0 the default path for the cookie is now '/'
