### ISSUE TITLE
What is the current stable version?

### ISSUE THREAD

**Issue by alexweissman** [gbirke/rememberme#17]
I noticed there is a branch `version_2`, but no commits have been made to that branch for nearly a year.  `master`, on the other hand, appears to have some recent commits.

It also appears that the [last release](https://github.com/gbirke/rememberme/releases/tag/1.0.4) was from `master` over a year ago.  So, should we consider the `version_2` branch to be abandoned?

**Comment by gbirke** [comment]
The current stable version is dev-master.

I've rebased `version_2` to the current master and I'm planning to release it. However, I still want to do some improvements to the code example and add a `travis.yml` file.

**Comment by alexweissman** [comment]
Cool, looking forward to it!

**Comment by gbirke** [comment]
The current stable version is now 2.0
