### ISSUE TITLE
Minimum PHP version supported?

### ISSUE THREAD

**Issue by willemstuursma** [gbirke/rememberme#23]
Hi @gbirke!

What is the minimum PHP version you want to support? Currently, it is not specified in `composer.json`. 

Travis is still using PHP 5.6, so that's the one?

If you can confirm this or indicate you want to switch to 7.1, then I'll create a PR to make use of the new features in these PHP versions that are applicable to this library such as `hash_equals`.

**Comment by gbirke** [comment]
Thank you for noting the missing requirements in `composer.json`!

The minimum version supported by the 2.0 release is 5.6
The minimum version of the new 3.0 release will be 7.2.
