### ISSUE TITLE
Logout when multiple request - possible bug ? 

### ISSUE THREAD

**Issue by YannikFirre** [gbirke/rememberme#27]
Hello,

I have a issue with last rememberme repo. When I have several requests executed at the same time, the user is disconnected. Specifically, the cookie appears to be removed.

Bug or bad implementation of my own ? 

Thanks for your help :D

**Comment by gamukeat** [comment]
Yes, I have the same issue, every request renew token.
At the moment I disabled this function :

`		
if($result){
	return self::TRIPLET_FOUND;
}
/*
 if (!$result) {
   return self::TRIPLET_NOT_FOUND;
 } elseif ($result === sha1($token)) {
    return self::TRIPLET_FOUND;
 }
return self::TRIPLET_INVALID;
*/`
