### ISSUE TITLE
PHP Type Juggling vulnerability exists in plugin.

### ISSUE THREAD

**Issue by SecGus** [gbirke/rememberme#29]
Hello!

This plugin seems to have a type juggling vulnerability that could result in a conditional always returning true. This is due to the use of a weak comparison, instead of a strict one. 

I came across this after playing with a CMS that uses the plugin, known as "GRAV" CMS.

Here you can see the vulnerable line:
`if($username == $_POST['username'] && $password == $_POST['password']) {`

Which exists in the file:
/birke/rememberme/example/action.php:

Since this is a weak comparison, it does not check types, and will return true if:
![image](https://user-images.githubusercontent.com/61525295/80034263-09cd1080-84e6-11ea-9749-57196fbc8eaa.png)

Let me know if further details are required. An example fix would simply be replacing the "==" with "===".

**Comment by gbirke** [comment]
Thank you for pointing this out!

The issue was fixed in Version 2.0
