### ISSUE TITLE
Is this project "production-ready"?

### ISSUE THREAD

**Issue by alexweissman** [gbirke/rememberme#9]
I'm thinking about using it to deploy Improved Persistent Sessions in my [user management script](https://github.com/alexweissman/UserFrosting).

**Comment by gbirke** [comment]
Depends on what you mean by "production-ready". I've 
- used the library in my own project
- taken the utmost care to implement the method correctly, 
- clearly described the purpose and limitations of the library,
- written unit tests
- had some constructive comments from people who used the library

**Comment by alexweissman** [comment]
Yup, that sounds about right - all of those things are better than if I were to start from scratch.  Thanks, and I'll let you know how it turns out!
